{% set name = "vega-cli" %}
{% set version = "5.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vega/vega/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fd5fc5eee61b0ecb9c30f148fd5e57c12b915329e9ccf9eccc517ea0c4a3b38b

build:
  number: 0
  skip: true  # [nodejs == 14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python >=3.7,<3.12
    - nodejs    # [not win]
    - make      # [not win]
    - rsync     # [linux]
    - pkg-config
  host:
    - nodejs
    - cairo     # [not win]
    - freetype  # [not win]
    - giflib    # [not win]
    - glib      # [not win]
    - libjpeg-turbo       # [not win]
    - libpng    # [not win]
    - pango     # [not win]
    - yarn <2   # [not win]
  run:
    - nodejs
    - pango  # [not win]

test:
  commands:
    - curl -L https://raw.githubusercontent.com/vega/vega/master/docs/examples/bar-chart.vg.json > test.json
    - vg2pdf test.json > test.pdf

about:
  home: https://vega.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Command line interface of the VEGA visualization grammar
  description: |
    The vega-cli package includes three node.js-based command line utilities -
    vg2pdf, vg2png, and vg2svg - for rendering static visualization images.
    These commands render to PDF, PNG, or SVG files, respectively.
  doc_url: https://vega.github.io/vega/usage/#cli
  dev_url: https://github.com/vega/vega

extra:
  recipe-maintainers:
    - johanneskoester
    - xhochy
