{% set name = "vega-cli" %}
{% set version = "5.17.0" %}
{% set sha256 = "f5fa1f605ed03598ad1413bc86f45f63d1652ef9f3c2c130180a45a36a9d8f10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vega/vega/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g vega-cli@{{ version }}

requirements:
  build:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - npm list -g vega-cli
    - curl -L https://raw.githubusercontent.com/vega/vega/master/docs/examples/bar-chart.vg.json > test.json
    - vg2pdf test.json > test.pdf
  requires:
    - nodejs

about:
  home: https://vega.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Command line interface of the VEGA visualization grammar'
  description: |
    The vega-cli package includes three node.js-based command line utilities -
    vg2pdf, vg2png, and vg2svg - for rendering static visualization images.
    These commands render to PDF, PNG, or SVG files, respectively.
  doc_url: https://vega.github.io/vega/usage/#cli
  dev_url: https://github.com/vega/vega

extra:
  recipe-maintainers:
    - johanneskoester
