{% set name = "vega-cli" %}
{% set version = "5.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [osx]
  number: 0
  script: $PREFIX/bin/npm install -g vega-cli@{{ version }} && cp $PREFIX/lib/node_modules/vega-cli/LICENSE $SRC_DIR  # [linux]
  script: '%PREFIX%\npm install -g --loglevel verbose vega-cli@{{ version }} && DIR %PREFIX%\node_modules\vega-cli && COPY %PREFIX%\node_modules\vega-cli\LICENSE %SRC_DIR%'  # [win]

requirements:
  build:
    - nodejs
  run:
    - nodejs

test:
  files:
    - test.json
  commands:
    - vg2pdf test.json > test.pdf

about:
  home: https://vega.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Command line interface of the VEGA visualization grammar'
  description: |
    The vega-cli package includes three node.js-based command line utilities -
    vg2pdf, vg2png, and vg2svg - for rendering static visualization images.
    These commands render to PDF, PNG, or SVG files, respectively.
  doc_url: https://vega.github.io/vega/usage/#cli
  dev_url: https://github.com/vega/vega

extra:
  recipe-maintainers:
    - johanneskoester
